name: Angular Build

on:
  push:
    branches: [ main ]

jobs:
  Frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Angular ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: npm i
    - run: ng build
    - run: pm2 restart 0