name: Angular

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Angular ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: pm2 restart 0
  job2:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: npm i
    - run: pm2 restart 1